
#spring:
#  profiles:
#    active: a

##  修改端口
#server:
#  port: 80
#

spring:
  profiles:
    actice: a
server:
  port: 80

#分页pageHelper
pagehelper:
#  配置使用哪种数据库语言，不配置的话pageHelper也会自动检测
  helper-dialect: mysql
#  配置分页参数合理化功能，默认是false。
  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页；
  #禁用合理化时，如果pageNum<1或pageNum>总页数会返回空数据。
  reasonable: true
  support-methods-arguments: true